# configuracoes gerais
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/adotepets
    username: sa_adotepets
    password: sa_adotepets

  jpa:
    show-sql: true

  flyway:
    enabled: false

# informacoes do sistema
info:
  app:
    version: 1.0.0

# configuracoes do actuator
management:
  endpoint:
    logfile:
      external-file: /${user.home}/${spring.application.name}.log

# configuracoes de logging
logging:
  file: /${user.home}/${spring.application.name}.log
#  level:
#    org:
#      springframework.security: debug
#      hibernate.type: trace
